site_name: prefect-symphony
site_url: https://PrefectHQ.github.io/prefect-symphony
repo_url: https://github.com/PrefectHQ/prefect-symphony
edit_uri: /edit/main/docs/
theme:
  name: material
  favicon: img/favicon.ico
  palette:
    primary: blue
    accent: blue
  icon:
    repo: fontawesome/brands/github
  logo:
    img/prefect-logo-white.png
  font:
    text: Inter
    code: Source Code Pro
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - admonition
    - attr_list
    - codehilite
    - md_in_html
    - meta
    - pymdownx.highlight:
        use_pygments: true
    - pymdownx.superfences
    - pymdownx.tabbed
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: True
            show_object_full_path: False
            show_category_heading: False
            show_bases: False
            show_signature: False
            heading_level: 1
      watch:
        - prefect_symphony/
        - README.md

nav:
    - Home: index.md
    - Admin: admin.md
    - App: app.md
    - Audittrail: audittrail.md
    - Authenticate: authenticate.md
    - Channelco: channelco.md
    - Companycert: companycert.md
    - Connection: connection.md
    - Credentials: credentials.md
    - Datafeeds: datafeeds.md
    - Dlp: dlp.md
    - Events: events.md
    - File Ext: file_ext.md
    - Files: files.md
    - Health: health.md
    - Idm: idm.md
    - Im: im.md
    - Info: info.md
    - Languages: languages.md
    - Logout: logout.md
    - Message: message.md
    - Onboarding: onboarding.md
    - Podcert: podcert.md
    - Presence: presence.md
    - Pubkey: pubkey.md
    - Rest: rest.md
    - Room: room.md
    - Sessioninfo: sessioninfo.md
    - Signals: signals.md
    - Stream: stream.md
    - Streams: streams.md
    - System: system.md
    - User: user.md
    - Users: users.md
    - Util: util.md
    
    - Models:
        - Channelco: models/channelco.md
        